package py.com.cdco.financespy.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val DASHBOARD = "dashboard"
    const val BUDGETS = "budgets"
    const val TRANSACTIONS = "transactions"
    const val RULES = "rules"
    const val GOALS = "goals"
    const val RECEIVABLES = "receivables"
    const val REPORTS = "reports"
    const val FLEET = "fleet"
    const val FLEET_VEHICLE_DETAIL = "fleet_vehicle/{vehicleId}"
    const val ACCOUNT_DETAIL = "account/{accountId}"
    const val RULE_DETAIL = "rule/{ruleId}"
    const val RULE_FORM = "rule_form?ruleId={ruleId}"
    const val GOAL_DETAIL = "goal/{goalId}"
    const val GOAL_FORM = "goal_form?goalId={goalId}"
    const val RECEIVABLE_DETAIL = "receivable/{receivableId}"
    const val RECEIVABLE_FORM = "receivable_form?receivableId={receivableId}"
    const val PRODUCTS = "products"
    const val PRODUCT_FORM = "product_form?productId={productId}"
    const val SALES = "sales"
    const val SALE_DETAIL = "sale/{saleId}"
    const val SALE_FORM = "sale_form?saleId={saleId}"
    const val PURCHASE_ORDERS = "purchase_orders"
    const val PURCHASE_ORDER_DETAIL = "purchase_order/{purchaseOrderId}"
    const val PURCHASE_ORDER_FORM = "purchase_order_form?purchaseOrderId={purchaseOrderId}"
    const val BUDGET_ALLOCATION_EDITOR = "budget_editor/{budgetId}"
    const val TRANSACTION_FORM = "transaction_form?transactionId={transactionId}"
    const val SETTINGS = "settings"
    const val NAV_CUSTOMIZATION = "nav_customization"

    fun accountDetail(accountId: String) = "account/$accountId"
    fun ruleDetail(ruleId: String) = "rule/$ruleId"
    fun ruleFormEdit(ruleId: String) = "rule_form?ruleId=$ruleId"
    fun ruleFormCreate() = "rule_form"
    fun goalDetail(goalId: String) = "goal/$goalId"
    fun goalFormEdit(goalId: String) = "goal_form?goalId=$goalId"
    fun goalFormCreate() = "goal_form"
    fun receivableDetail(receivableId: String) = "receivable/$receivableId"
    fun receivableFormEdit(receivableId: String) = "receivable_form?receivableId=$receivableId"
    fun receivableFormCreate() = "receivable_form"
    fun productFormEdit(productId: String) = "product_form?productId=$productId"
    fun productFormCreate() = "product_form"
    fun saleDetail(saleId: String) = "sale/$saleId"
    fun saleFormEdit(saleId: String) = "sale_form?saleId=$saleId"
    fun saleFormCreate() = "sale_form"
    fun purchaseOrderDetail(purchaseOrderId: String) = "purchase_order/$purchaseOrderId"
    fun purchaseOrderFormEdit(purchaseOrderId: String) = "purchase_order_form?purchaseOrderId=$purchaseOrderId"
    fun purchaseOrderFormCreate() = "purchase_order_form"
    fun fleetVehicleDetail(vehicleId: String) = "fleet_vehicle/$vehicleId"
    fun budgetAllocationEditor(budgetId: String) = "budget_editor/$budgetId"
    fun transactionFormEdit(transactionId: String) = "transaction_form?transactionId=$transactionId"
    fun transactionFormCreate() = "transaction_form"
}
