package py.com.cdco.financespy.auth

import io.ktor.client.HttpClient
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.http.HttpStatusCode
import io.ktor.http.headersOf
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// Validates the OAuth `state` (CSRF) handling added for S7: a callback is
// only honored when its `state` matches the one generated by the immediately
// preceding buildAuthorizationUrl() call, and that pairing can only be used
// once.
class AuthRepositoryTest {

    private class FakeTokenStorage : TokenStorage {
        var access: String? = null
        var refresh: String? = null
        override suspend fun save(accessToken: String, refreshToken: String) {
            access = accessToken
            refresh = refreshToken
        }
        override suspend fun accessToken(): String? = access
        override suspend fun refreshToken(): String? = refresh
        override suspend fun clear() { access = null; refresh = null }
    }

    private fun stateFromUrl(url: String): String =
        url.substringAfter("&state=")

    private fun buildClient(tokenRequests: () -> Unit): HttpClient {
        val mockEngine = MockEngine { request ->
            when (request.url.encodedPath) {
                "/oauth/token" -> {
                    tokenRequests()
                    respond(
                        """{"access_token":"at","refresh_token":"rt","token_type":"Bearer","expires_in":3600}""",
                        HttpStatusCode.OK,
                        headersOf("Content-Type", "application/json")
                    )
                }
                else -> respond("Not Found", HttpStatusCode.NotFound)
            }
        }
        return HttpClient(mockEngine) {
            install(ContentNegotiation) {
                json(Json { ignoreUnknownKeys = true; isLenient = true })
            }
        }
    }

    @Test
    fun mismatchedStateIsRejectedWithoutCallingTokenEndpoint() = runTest {
        var tokenCalls = 0
        val http = buildClient { tokenCalls++ }
        val storage = FakeTokenStorage()
        val repo = AuthRepository(http, storage)

        repo.buildAuthorizationUrl() // arms a pending flow with its own state
        val result = repo.exchangeCode("some-code", "attacker-controlled-state")

        assertTrue(result.isFailure)
        assertEquals(0, tokenCalls)
        assertEquals(null, storage.access)
    }

    @Test
    fun missingStateIsRejected() = runTest {
        var tokenCalls = 0
        val http = buildClient { tokenCalls++ }
        val repo = AuthRepository(http, FakeTokenStorage())

        repo.buildAuthorizationUrl()
        val result = repo.exchangeCode("some-code", state = null)

        assertTrue(result.isFailure)
        assertEquals(0, tokenCalls)
    }

    @Test
    fun callbackWithNoPendingFlowIsIgnored() = runTest {
        var tokenCalls = 0
        val http = buildClient { tokenCalls++ }
        val repo = AuthRepository(http, FakeTokenStorage())

        // No buildAuthorizationUrl() call at all -- e.g. a cold app process
        // receiving a stray/replayed deep link.
        val result = repo.exchangeCode("some-code", "any-state")

        assertTrue(result.isFailure)
        assertEquals(0, tokenCalls)
    }

    @Test
    fun matchingStateSucceedsAndSavesTokens() = runTest {
        var tokenCalls = 0
        val http = buildClient { tokenCalls++ }
        val storage = FakeTokenStorage()
        val repo = AuthRepository(http, storage)

        val url = repo.buildAuthorizationUrl()
        val state = stateFromUrl(url)
        val result = repo.exchangeCode("some-code", state)

        assertTrue(result.isSuccess)
        assertEquals(1, tokenCalls)
        assertEquals("at", storage.access)
        assertEquals("rt", storage.refresh)
    }

    @Test
    fun stateCannotBeReplayedAfterASuccessfulExchange() = runTest {
        var tokenCalls = 0
        val http = buildClient { tokenCalls++ }
        val repo = AuthRepository(http, FakeTokenStorage())

        val url = repo.buildAuthorizationUrl()
        val state = stateFromUrl(url)
        assertTrue(repo.exchangeCode("some-code", state).isSuccess)

        // Same state, second callback (e.g. a replayed/duplicated deep link).
        val replay = repo.exchangeCode("some-code", state)
        assertFalse(replay.isSuccess)
        assertEquals(1, tokenCalls) // token endpoint not hit again
    }
}
