# frozen_string_literal: true

json.extract! budget, :id, :start_date, :end_date, :currency
json.budgeted_spending budget.budgeted_spending.to_f
json.expected_income budget.expected_income.to_f
json.actual_spending budget.actual_spending.to_f
json.actual_spending_cents budget.actual_spending_cents
json.allocated_spending budget.allocated_spending.to_f
json.allocated_spending_cents budget.allocated_spending_cents
json.available_to_spend budget.available_to_spend.to_f
json.available_to_spend_cents budget.available_to_spend_cents
json.percent_of_budget_spent budget.percent_of_budget_spent.to_f.round(1)
json.actual_income budget.actual_income.to_f
json.actual_income_cents budget.actual_income_cents
json.remaining_expected_income budget.remaining_expected_income.to_f
json.remaining_expected_income_cents budget.remaining_expected_income_cents
